spring:
  redis:
    host: 43.138.194.9
    port: 6379
    password: 313725190
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100